Create OCL.g4
antlr/grammars-v4 pull request #2678
Opened 2022-06-22 10:31 UTC by kevinlano

Parser for OCL2.4

2022-06-22 10:52 UTC, KvanTTT requested changes
Please reformat and simplify.

2022-06-22 10:52 UTC, KvanTTT commented on ocl/OCL.g4
> +    | 'interface' ID 'extends' ID '{' classBody? '}';
The common part can be extracted here and below:

```suggestion
interfaceDefinition
    : 'interface' ID ('extends' ID)? '{' classBody? '}'
    ;
```

Also, please use such formatting (we use it across all grammars in the repository):

```
rule
    : a1 (a2 | a3)
    | a4
    ...
    | an
    ;
```

2022-06-22 10:52 UTC, KvanTTT commented on ocl/OCL.g4
> +    | 'class' ID 'extends' ID '{' classBody? '}';
```suggestion
classDefinition
    : 'class' ID ('extends' ID)? '{' classBody? '}'
    ; 
```

2022-06-22 10:52 UTC, KvanTTT commented on ocl/OCL.g4
> +    ;
```suggestion
attributeDefinition
    : 'attribute' ID ('identity' | 'derived')? ':' type ';'
    | 'static' 'attribute' ID ':' type ';'
    ; 
```

2022-06-27 00:26 UTC, teverett commented
@kevinlano thanks for this, please fix the merge conflicts.

2022-06-27 19:17 UTC, teverett commented
@kevinlano  thanks for this.  I'll pull this PR and then format the code with:

https://github.com/antlr/Antlr4Formatter

If that works for you?

2022-06-28 10:05 UTC, kevinlano commented
Thanks Tom,
yes, that is fine,
Kevin
________________________________
From: Tom Everett ***@***.***>
Sent: 27 June 2022 20:17
To: antlr/grammars-v4 ***@***.***>
Cc: Lano, Kevin ***@***.***>; Mention ***@***.***>
Subject: Re: [antlr/grammars-v4] Create OCL.g4 (PR #2678)


@kevinlano<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkevinlano&data=05%7C01%7Ckevin.lano%40kcl.ac.uk%7C1189592a55fa43f98a9408da5871a4de%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637919542370534540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rUdjYFmJnV92cHYmruDA%2F9XPGqyI3FB%2FUBGxphfrEPY%3D&reserved=0> thanks for this. I'll pull this PR and then format the code with:

https://github.com/antlr/Antlr4Formatter<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fantlr%2FAntlr4Formatter&data=05%7C01%7Ckevin.lano%40kcl.ac.uk%7C1189592a55fa43f98a9408da5871a4de%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637919542370534540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FHMY0gSE5nwC2N9t%2B1M2A7Pi3NUGR6nsS8pOqiZ1C04%3D&reserved=0>

If that works for you?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fantlr%2Fgrammars-v4%2Fpull%2F2678%23issuecomment-1167777468&data=05%7C01%7Ckevin.lano%40kcl.ac.uk%7C1189592a55fa43f98a9408da5871a4de%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637919542370534540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=82t9p36SDdOY8R64jVn3Yr00v5V3AHCQLTt5eWX6VkY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABU4GKECEN6VSIUYXWITELDVRH43TANCNFSM5ZPWTRHA&data=05%7C01%7Ckevin.lano%40kcl.ac.uk%7C1189592a55fa43f98a9408da5871a4de%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637919542370534540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=swkQBNZzpExChWfjKFfBHm5o9LMd0sUSngzwzGmmmIk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-28 10:33 UTC, KvanTTT commented
It looks like the request already is not actual.

2022-06-28 10:33 UTC, closed without merging