#1228 - ArangoDb - grammar and tests
antlr/grammars-v4 pull request #2963
Opened 2022-12-15 12:02 UTC by mlorek

2022-12-15 12:21 UTC, KvanTTT requested changes
Thank you for the new grammar but please factor common parts and fix formatting.

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    ;
I suggest factoring:

```suggestion
data_access_query
    : with_collection_list? ( for_op* return_expr
                            | FOR v=id_ (',' e=id_ (',' p=id_)? )?
                             IN (numeric_literal ('..' numeric_literal)? )?
                             (OUTBOUND | INBOUND | ANY) expr
                             (GRAPH expr | collection_list) // collections support direction: ANY
                             (PRUNE expr)?
                             filter*
                             options_?
                             return_expr? )
    ;
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    ;
```suggestion
data_modification_query
    : with_collection_list? for_op*
        ( INSERT object_literal in_into collection options_?  
        | UPDATE (expr WITH)? object_literal IN collection options_?
        | REPLACE (expr WITH)? object_literal IN collection options_?
        | (REMOVE expr IN collection options_?)+
        | UPSERT expr INSERT expr (UPDATE | REPLACE) expr IN collection options_?
        )
      return_expr?
    ;
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    ;
```suggestion
collect
    : COLLECT ( expr (INTO expr)?
              | expr (INTO id_ KEEP id_)?
              | expr WITH COUNT INTO id_
              | expr? aggregate_assign (INTO id_)?
              | WITH COUNT INTO id_
              )
      options_?
    ;
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    ;
```suggestion
window
    : WINDOW (expr WITH)? object_literal aggregate_assign
    ;
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    | TRUE | FALSE
```suggestion
    | TRUE
    | FALSE
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    : NEW | OLD
Please fix formatting (first-level alternatives on new lines):

```suggestion
    : NEW
    | OLD
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    : id_ | BIND_PARAMETER_COLL
```suggestion
    : id_
    | BIND_PARAMETER_COLL
```

2022-12-15 12:21 UTC, KvanTTT commented on aql/ArangoDbParser.g4
> +    | '{' id_ (',' id_)* '}' // accepted in RETURN clause
```suggestion
    : '{' (pair_list | id_ (',' id_)*)? '}' // accepted in RETURN clause
```

2022-12-16 09:29 UTC, mlorek commented
php build fails with
![image](https://user-images.githubusercontent.com/7452353/208067410-73f4c3b3-2878-44ec-97cc-0513a6ebe6f3.png)

2022-12-16 11:47 UTC, KvanTTT commented
@kaby76 could you please take a look at PHP build? Does it make sense to restart the build?

2022-12-16 12:38 UTC, kaby76 commented
The PHP target for this grammar uses more than the available memory in PHP 8.1.12. If it doesn't work for that version of PHP, then it won't work for 8.0.x, which is being used in the CI build. In this case, php doesn't terminate. Fortunately, we have the trwdog app making sure this doesn't kill the build so much that intervention is required.

But, the target doesn't work well with PHP. I suggest you just add "aql" to the [skip list for PHP](https://github.com/antlr/grammars-v4/blob/master/_scripts/skip-php.txt). Doesn't matter where, but in alphabetic order is preferred.

Now, as far as what the parser fails on is "for.aql". This is a 2-line query. The grammar is ambiguous for expression, requiring a very, very large read ahead to determine. I think the grammar has some problems. But, this grammar should not fail like this for PHP. An issue should be created in antlr/antlr4 to determine why it's so bad.

2022-12-16 12:48 UTC, kaby76 commented
OK, the problem with this grammar is the choice between `expr : ... expr (',' expr)+ ...` and `expr : ... expr '[' (expr_list | '*') ']' ...` in which we have `expr_list : expr (',' expr)*;`. It cannot decide where the expr ends and where it begins in the expr_list. Suggest the alt be `expr '[' (expr | '*') ']'`, or something like that.

2022-12-16 13:45 UTC, mlorek commented
> Yes, this looks good. Does it work with "mvn clean test"? If so, then this should work for PHP--and speed up all the other targets as well.

it did work locally

2022-12-16 14:18 UTC, kaby76 commented
Oh well--still doesn't work for PHP. After the build settles down, add aql to the skip-php.txt file to get past this problem for now.

2022-12-16 14:54 UTC, kaby76 commented
I added a "-d memory_limit=4G" option to the call to php on the command line, and although it runs longer, it still fails with a timeout. All tests parse fine except for.aql, and quickly. So, there is something quite wrong with the PHP target. This needs to be raised in github.com/antlr/antlr4/issues. Working with 4.11.1 and PHP 8.1.12

2022-12-16 15:49 UTC, KvanTTT approved these changes

2022-12-16 15:49 UTC, merged

2022-12-16 23:34 UTC, kaby76 commented
The PR was merged, but the build was still broken. skip-php.txt should contain aql. I'll submit a PR to fix this, and an issue in antlr/antlr4 for the problem in parsing for.aql.

2022-12-17 15:59 UTC, kaby76 commented
The out of memory condition for aql/for.aql has been observed in another grammar. https://github.com/antlr/antlr-php-runtime/issues/12#issuecomment-1356316535 Tracking it down. (We could change the grammar, but then the bug will still be there.)