add plsql grammar
antlr/grammars-v4 pull request #3007
Opened 2023-01-11 06:40 UTC by hellozrh

1. oracle 21c grammar: alter table with MEMOPTIMIZE clause.
2. add flashback_table.
3. fix index_org_table_clause.

2023-01-11 17:21 UTC, msagca commented
@hellozrh,

Title is misleading. You've made changes to an already existing grammar.

2023-02-12 18:05 UTC, KvanTTT requested changes

2023-02-12 18:05 UTC, KvanTTT commented on sql/plsql/PlSqlLexer.g4
> +MEMOPTIMIZE:                  'MEMOPTIMIZE';
I guess it also should be added to `non_reserved_keywords_in_12c` or to `non_reserved_keywords_pre12c`.

2023-02-12 18:05 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +      )
Please fix whitespaces and parentheses:

```suggestion
      ( ((SCN | TIMESTAMP) expression | RESTORE POINT restore_point) ((ENABLE | DISABLE) TRIGGERS)?
        | BEFORE DROP (RENAME TO tableview_name)?
      )
```

2023-02-12 18:05 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    | SYS
I guess it should be either in `non_reserved_keywords_in_12c` or in `non_reserved_keywords_pre12c` but not in both.

2023-02-16 15:18 UTC, merged