#3043 - create table - update to oracle 21
antlr/grammars-v4 pull request #3071
Opened 2023-02-13 08:35 UTC by mlorek

create table stmt update to oracle 21

2023-02-14 20:54 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    : HASHING USING sha2_512_quoted VERSION v1_quoted
Can `sha2_512_quoted` and `v1_quoted` just be inlined? What is the purpose of primitive parser rules?

```suggestion
    : HASHING USING SHA2_512_Q VERSION V1_Q
```

2023-02-17 08:17 UTC, mlorek commented
@KvanTTT are you ok with the changes?

2023-02-17 13:38 UTC, KvanTTT requested changes
Sorry, but could you split tokens reordering (for instance, I see `A_LETTER` just was moved below) and feature changes? It's hard for reviewing when they are mixed.

2023-02-17 15:04 UTC, KvanTTT requested changes

2023-02-17 15:04 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +        (UNUSABLE BEGINNING WITH (CURRENT EDITION | EDITION edition_name | NULL_ EDITION) )?
```suggestion
        (UNUSABLE BEGINNING WITH ((CURRENT | NULL_) EDITION | EDITION edition_name) )?
```

2023-02-17 15:04 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +        unusable_edition_clause
I suggest changing it to optional:

```suggestion
        unusable_edition_clause?
```

And making `unusable_edition_clause` not empty.

2023-02-17 15:04 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    : EVALUATE USING (CURRENT EDITION | EDITION edition_name | NULL_ EDITION)
```suggestion
    : EVALUATE USING ((CURRENT | NULL_) EDITION | EDITION edition_name)
```

2023-02-17 17:26 UTC, KvanTTT requested changes

2023-02-17 17:26 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    | SYS
Not only `MEMOPTIMIZE` and `SYS`, but all new tokens from this pull request. They can be identifiers as well.

2023-02-18 14:27 UTC, KvanTTT approved these changes

2023-02-18 14:28 UTC, merged