[Tsql] Fix grammar for foreign_key_options
antlr/grammars-v4 pull request #3091
Opened 2023-02-17 09:14 UTC by jiangtao69039

Previous syntax does not match the follow statement:
```sql
ALTER TABLE t_order_item ADD PRIMARY KEY (order_id), FOREIGN KEY (order_id) REFERENCES t_order (order_id) ON UPDATE CASCADE  ON DELETE CASCADE
```

**ON UPDATE CASCADE**  and  **ON DELETE CASCADE**  When they appear at the same time, the order is irrelevant

2023-02-17 13:16 UTC, KvanTTT commented
Please add a test to [sql/tsql/examples](https://github.com/antlr/grammars-v4/tree/master/sql/tsql/examples) directory that covers the suggested changes.

2023-02-17 13:17 UTC, KvanTTT requested changes
Please add a test to [sql/tsql/examples](https://github.com/antlr/grammars-v4/tree/master/sql/tsql/examples) directory that covers the suggested changes.

2023-02-20 01:12 UTC, jiangtao69039 commented
ok, i have added

2023-02-20 14:56 UTC, KvanTTT approved these changes

2023-02-20 14:56 UTC, merged