snowflake: fix parsing of `COMMENT` in column declaration
antlr/grammars-v4 pull request #3098
Opened 2023-02-18 20:15 UTC by michael-the1

Fix parsing of `COMMENT` in the column declaration of a `CREATE TABLE` statement. A `COMMENT` in a column declaration is done _without_ the equals (`=`) sign (see [documentation](https://docs.snowflake.com/en/sql-reference/sql/create-table)).

While there, replace `COMMENT EQ string` with the already existing `comment_clause`.

2023-02-18 20:46 UTC, KvanTTT requested changes
Thanks for the contribution and welcome to ANTLR grammars repository!

But please remove redundant parentheses.

2023-02-18 20:46 UTC, KvanTTT commented on sql/snowflake/SnowflakeParser.g4
> +    : CREATE CONNECTION if_not_exists? id_ ( ( comment_clause )? | (AS REPLICA OF id_ DOT id_ DOT id_ ( comment_clause )?) )
```suggestion
    : CREATE CONNECTION if_not_exists? id_ ( comment_clause? | (AS REPLICA OF id_ DOT id_ DOT id_ comment_clause?) )
```

2023-02-18 20:46 UTC, KvanTTT commented on sql/snowflake/SnowflakeParser.g4
> +    : CREATE or_replace? TAG if_not_exists? id_ ( comment_clause )?
```suggestion
    : CREATE or_replace? TAG if_not_exists? id_ comment_clause?
```

2023-02-18 20:51 UTC, michael-the1 commented
> Thanks for the contribution and welcome to ANTLR grammars repository!
> 
> But please remove redundant parentheses.

Thanks! I find-replaced them without looking, should've known better 😂

2023-02-18 21:19 UTC, KvanTTT approved these changes

2023-02-18 21:20 UTC, merged

2023-02-19 10:45 UTC, MasterKuat commented
Hi @michael-the1,
As options could appear in any order full_col_decl grammar should be something like :
```
full_col_decl
    : col_decl
        (collate|(COMMENT string)|default_value|not_null|with_masking_policy|with_tags|inline_constraint)*
    ;

```
By the way, not sure of syntax as I'm a noob with antlr but I test it and seems good.
Many thanks for your work 😃

2023-02-19 13:38 UTC, michael-the1 commented
@MasterKuat Yes, I also ran into that and came to the same solution. I will probably open a PR for it next week, or you can totally do it! I'm also pretty new at ANTLR, but I found contributing like this quite easy. Just add a few test statements and it should be good to go.