with sql parser
antlr/grammars-v4 pull request #3129
Opened 2023-02-23 03:16 UTC by caicancai

Common Table Expression (CTE) was introduced in MySQL 5.7 WITH the WITH statement to support the syntax of CTE. CTE is a general syntax used to improve the readability, maintainability, and reuse of SQL statements. It can define one or more expressions using simple syntax and use them to build more complex expressions into the query, making the query easier to understand and debug. In this sense, Ctes are important for data integration in MySQL 5.7.

2023-02-23 03:38 UTC, caicancai commented
I in the g4 file condition with keyword, support with keyword parsing
```
withStatement
  : 'WITH' commonTableExpressions (',' commonTableExpressions)*
  ;
```

2023-02-23 10:08 UTC, caicancai commented
update MySqlParser.g4

2023-02-23 12:49 UTC, KvanTTT requested changes
Thanks for the contribution and welcome to ANTLR grammars repository!

But please add a sample to [sql/mysql/Positive-Technologies/examples](https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies/examples) that covers suggested changes.

2023-02-24 02:09 UTC, caicancai commented
The original MySqlParser.g4 does not support the parsing of cte sql, but through commonTableExpressions extension, the MySqlParser.g4 supports the parsing of cte sql

2023-02-24 12:41 UTC, caicancai commented
@KvanTTT

2023-02-24 14:25 UTC, KvanTTT approved these changes

2023-02-24 14:26 UTC, merged