[PlSql] Support of create database
antlr/grammars-v4 pull request #3168
Opened 2023-03-02 02:59 UTC by hellozrh

[PlSql] Support of create database

2023-03-02 03:05 UTC, hellozrh commented
[PlSql] Support of create database #3167

2023-03-02 13:51 UTC, KvanTTT commented on sql/plsql/PlSqlLexer.g4
> +LEAF:                         'LEAF';
Please add this token to the list of non reserved keywords.

2023-03-02 13:52 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +     | USER SYSTEM IDENTIFIED BY password_value
I suggest simplifying:

```suggestion
     ( USER (SYS | SYSTEM) IDENTIFIED BY password_value
```

2023-03-02 13:54 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    | (ARCHIVELOG | NOARCHIVELOG)
```suggestion
    | (MAXLOGFILES | MAXLOGMEMBERS | MAXLOGHISTORY) UNSIGNED_INTEGER
    | ARCHIVELOG
    | NOARCHIVELOG
```

2023-03-02 13:54 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    | SYSAUX DATAFILE file_specification (',' file_specification)*
```suggestion
    | SYSAUX? DATAFILE file_specification (',' file_specification)*
```

2023-03-02 13:55 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +     | NATIONAL CHARACTER SET char_set_name
```suggestion
     | (MAXDATAFILES | MAXINSTANCES) UNSIGNED_INTEGER
     | NATIONAL? CHARACTER SET char_set_name
```

2023-03-04 14:55 UTC, KvanTTT requested changes

2023-03-04 14:55 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +
The same parse rule already exists: https://github.com/antlr/grammars-v4/blob/ef698f1a02103d7e026ce7b3ea0b4120d4fc487c/sql/plsql/PlSqlParser.g4#L4060-L4063

Please reuse it.

2023-03-06 01:18 UTC, closed without merging