apache drill grammar
antlr/grammars-v4 pull request #3202
Opened 2023-03-09 15:06 UTC by mlorek

2023-03-09 15:28 UTC, mlorek commented
@kaby76 how can I see more details about the following:
`DrillParser.ts(7245,9): error TS2393: Duplicate function implementation.`

2023-03-09 16:04 UTC, kaby76 commented
> @kaby76 how can I see more details about the following: `DrillParser.ts(7245,9): error TS2393: Duplicate function implementation.`

For the typescript test.sh, it looks like I didn't redirect correctly. I will check.

```
03/09-10:49:07 ~/fb/grammars-v4/sql/drill/Generated-TypeScript
$ make
bash build.sh
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 19 packages, and audited 20 packages in 3s

found 0 vulnerabilities
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 11 packages, and audited 12 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> i@1.0.0 build
> tsc -p tsconfig.json

DrillParser.ts:7245:9 - error TS2393: Duplicate function implementation.

7245  public expression_list(): ExpressionContext[] {
             ~~~~~~~~~~~~~~~

DrillParser.ts:7296:9 - error TS2393: Duplicate function implementation.

7296  public expression_list(): Expression_listContext {
             ~~~~~~~~~~~~~~~

DrillParser.ts:7378:9 - error TS2393: Duplicate function implementation.

7378  public expression_list(): ExpressionContext[] {
             ~~~~~~~~~~~~~~~

DrillParser.ts:7435:9 - error TS2393: Duplicate function implementation.

7435  public expression_list(): Expression_listContext {
             ~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: DrillParser.ts:7245

mingw32-make: *** [makefile:3: build] Error 2
```

2023-03-09 16:12 UTC, kaby76 commented
Looks like the all wise, all knowing, great programmers of tsc decided to output the error messages from the compiler to something other than stderr and stdout. I'm not sure yet how I can redirect TypeScript error messages.

2023-03-09 16:40 UTC, kaby76 commented
Instead of disabling TypeScript, you can just rename "expression_list" to "expression_list_". It's a "symbol conflict".

2023-03-09 17:31 UTC, KvanTTT requested changes
Please remove redundant parentheses.

2023-03-09 17:31 UTC, KvanTTT commented on sql/drill/DrillLexer.g4
> +fragment DEC_DOT_DEC : (DEC_DIGIT+ '.' DEC_DIGIT+ |  DEC_DIGIT+ '.' | '.' DEC_DIGIT+);
Useless parentheses:

```suggestion
fragment DEC_DOT_DEC : DEC_DIGIT+ '.' DEC_DIGIT+ |  DEC_DIGIT+ '.' | '.' DEC_DIGIT+;
```

2023-03-09 17:31 UTC, KvanTTT commented on sql/drill/DrillLexer.g4
> +CHAR_LITERAL      : '\'' (~['\\\r\n]) '\'';
```suggestion
CHAR_LITERAL      : '\'' ~['\\\r\n] '\'';
```

2023-03-09 17:31 UTC, KvanTTT commented on sql/drill/DrillLexer.g4
> +REAL_LITERAL      : (DECIMAL_LITERAL | DEC_DOT_DEC) ('E' [+-]? DEC_DIGIT+);
```suggestion
REAL_LITERAL      : (DECIMAL_LITERAL | DEC_DOT_DEC) 'E' [+-]? DEC_DIGIT+;
```

2023-03-09 17:31 UTC, KvanTTT commented on sql/drill/DrillParser.g4
> +    : ANALYZE TABLE (table_name | TABLE'(' id_'(' param_list ')' ')')?
Missing spaces:

```suggestion
    : ANALYZE TABLE (table_name | TABLE '(' id_ '(' param_list ')' ')')?
```

2023-03-09 17:52 UTC, kaby76 commented
The problem with redirecting the output from the TypeScript is solved using "tsc --pretty -p tsconfig.json". The fix will be in with https://github.com/antlr/grammars-v4/pull/3195

2023-03-13 13:21 UTC, mlorek commented
@KvanTTT all ok?

2023-03-13 13:22 UTC, KvanTTT approved these changes

2023-03-13 13:23 UTC, merged