Update vba.g4
antlr/grammars-v4 pull request #3336
Opened 2023-04-20 03:26 UTC by Xenios91

Should resolve issue #3334

2023-04-20 07:56 UTC, msagca commented on vba/vba.g4
> +	| valueStmt (WS? DIV WS? | WS? MULT WS? ) valueStmt 	# vsDivMult
You can leave `WS?` outside the parentheses:
```antlr
| valueStmt WS? (DIV | MULT) WS? valueStmt
```

2023-04-20 08:04 UTC, msagca commented
@Xenios91 

The order of operations still isn't correct, e.g. `NOT` is below all the other logical operators while it has the highest precedence. Also, the relational operators should be grouped as well. Please refer to the table I posted in #3334.

2023-04-20 14:06 UTC, KvanTTT requested changes
Thanks for the contribution but please fix issues mentioned by @msagca and me.

2023-04-20 14:06 UTC, KvanTTT commented on vba/vba.g4
> +	| valueStmt (WS? PLUS WS? | WS? MINUS WS?) valueStmt 	# vsAddMinus
```suggestion
	| valueStmt WS? (PLUS | MINUS) WS? valueStmt 	# vsAddMinus
```

2023-04-21 01:01 UTC, Xenios91 commented
Alright, I believe that should resolve the issues?

2023-04-21 01:04 UTC, Xenios91 commented
Alright, I believe that should resolve the issues requested to be fixed?

2023-04-22 08:21 UTC, msagca commented
@Xenios91 

I just noticed that the order still isn't correct. Relational operators should come just before the logical operators and below mul/div/add/sub/mod.

2023-04-22 19:09 UTC, Xenios91 commented
> @Xenios91
> 
> I've just noticed that the order still isn't correct. Relational operators should come just before the logical operators (after pow, mul, div, mod, add, sub and bitwise and).

Hows that look now?

2023-04-22 19:21 UTC, msagca commented
@Xenios91 

Looks good to me.

2023-04-23 03:56 UTC, Xenios91 commented
awesome, thanks for the guidance.

2023-04-29 12:10 UTC, KvanTTT approved these changes

2023-04-29 12:13 UTC, merged

2023-04-29 12:13 UTC, KvanTTT commented
Yes, everything is ok.

@Xenios91 welcome to ANTLR grammars repository!