[antlr3] Removed useless parentheses.
antlr/grammars-v4 pull request #3368
Opened 2023-05-04 09:34 UTC by kaby76

Removed useless parentheses in antlr3.

2023-05-04 17:03 UTC, KvanTTT requested changes
The grammar actually contains other rules with useless parenteses but unfortunately it's not possible to comment not changed code.

Could you please also remove useless parentheses from these lines?

* https://github.com/antlr/grammars-v4/blob/master/antlr/antlr3/ANTLRv3Parser.g4#L94
* https://github.com/antlr/grammars-v4/blob/master/antlr/antlr3/ANTLRv3Parser.g4#L109
* https://github.com/antlr/grammars-v4/blob/master/antlr/antlr3/ANTLRv3Parser.g4#L155

2023-05-05 09:34 UTC, kaby76 commented
@KvanTTT  Thanks for noting these. It's been hard to get the patterns for useless parentheses correct. Changes added. And, here is the new script.
```
#!/bin/bash
echo Finding useless parentheses in grammars...
for i in `find . -name desc.xml | grep -v Generated\*`
do
  echo $i
  d=`dirname $i`
  pushd $d > /dev/null 2>&1
  trparse -t ANTLRv4 *.g4 | trxgrep '
	(: Find all blocks... :)
	//block[
		(: except not one of these ... :)
		not(./parent::ebnf/blockSuffix and ./altList/OR) and
		not(./parent::ebnf/blockSuffix and count(./altList/alternative/element) > 1) and
		not(./altList/OR and ../../following-sibling::element) and
		not(./altList/OR and ../../preceding-sibling::element)
	]/ancestor::parserRuleSpec' | trtext

  trparse -t ANTLRv4 *.g4 | trxgrep '
	(: Find all blocks... :)
	//lexerBlock[
		(: except not one of these ... :)
		not(./parent::lexerElement/ebnfSuffix and ./lexerAltList/OR) and
		not(./parent::lexerElement/ebnfSuffix and count(./lexerAltList/lexerAlt/lexerElements/lexerElement) > 1) and
		not(./lexerAltList/OR and ../following-sibling::lexerElement) and
		not(./lexerAltList/OR and ../preceding-sibling::lexerElement)
	]/ancestor::lexerRuleSpec' | trtext
  popd > /dev/null 2>&1
done
```

2023-05-05 10:45 UTC, KvanTTT approved these changes

2023-05-05 10:45 UTC, merged

2023-05-05 10:45 UTC, KvanTTT commented
Thanks a lot!