[antlr4] Remove useless parentheses
antlr/grammars-v4 pull request #3369
Opened 2023-05-04 11:33 UTC by kaby76

Remove the useless parentheses in the antlr4 grammar. Update to latest trgen since Cpp target is not working with additional cpp files.

2023-05-04 17:12 UTC, KvanTTT requested changes

2023-05-04 17:12 UTC, KvanTTT commented on .github/workflows/main.yml
> +        for i in trgen triconv trwdog trxml trxml2; do dotnet tool install -g $i --version 0.20.17; done
Version update doesn't relate to PR title. Please extract these changes to another PR.

2023-05-05 09:44 UTC, kaby76 commented
@KvanTTT Fixed. The PR now has modified only ANTLRv4Parser.g4 and desc.xml. The desc.xml is to get the build to work with Cpp, making explicit the "top-level" grammars that should be run through the Antlr4 tool.

2023-05-05 10:47 UTC, KvanTTT approved these changes

2023-05-05 10:48 UTC, merged