[ada95] Remove useless parentheses.
antlr/grammars-v4 pull request #3394
Opened 2023-05-09 14:54 UTC by kaby76

Removed useless parentheses that I missed previously.

2023-05-10 17:22 UTC, KvanTTT approved these changes

2023-05-10 17:23 UTC, KvanTTT requested changes

2023-05-10 19:21 UTC, kaby76 commented on ada/ada95/Ada95Lexer.g4
>  STRING_LITERAL_   : '"' ('""' | ~('"') )* '"';
Added change https://github.com/antlr/grammars-v4/pull/3394/commits/149bd320685ea8caf0a335b188f7cd35d39a7fdb

2023-05-11 11:00 UTC, kaby76 commented
Something is really messed up with Github Actions. Github only reports "This job failed", and doesn't provide any useful information to resolve the issue. I'm seeing the same thing over in github.com/antlr/antlr4 in the last day or two: https://github.com/antlr/antlr4/actions/runs/4938717676/jobs/8828784761

2023-05-12 15:01 UTC, KvanTTT approved these changes

2023-05-12 15:02 UTC, merged