[PLSQL] Single statement without ending semicolon
antlr/grammars-v4 pull request #3556
Opened 2023-06-26 07:34 UTC by mfvitale

In case of single statement without ending semicolon, do you think this should pass?

I think yes, since this query is valid. The statement should fail is is followed by another one. 

Any suggestion on how to fix?

2023-06-28 10:20 UTC, mfvitale commented
@KvanTTT To let single statement working without semicolon required lot of changes. Can I gently ask to a review?

2023-07-05 08:49 UTC, mfvitale commented
@KvanTTT Can you please help with `Parsing grammar /home/runner/work/grammars-v4/grammars-v4/sql/plsql/Generated-CSharp/PlSqlParser.g4
2023-06-30T09:10:52.9763475Z Process is taking longer than 300 seconds. Killing process.
2023-06-30T09:10:53.0751479Z Test failed.
2023-06-30T09:10:53.0776720Z  Test 00:08:18`

I need some guidance on how to figure out the issue here. Thanks.

2023-07-19 10:33 UTC, KvanTTT requested changes

2023-07-19 10:33 UTC, KvanTTT commented on sql/plsql/PlSqlLexer.g4
> +FILE_EXT:                     ('PKB' | 'PKS');
```suggestion
FILE_EXT:                     'PKB' | 'PKS';
```

2023-07-19 10:33 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    : sql_plus_command_no_semicolon? (((sql_plus_command | unit_statement) (SEMICOLON'/'? (sql_plus_command | unit_statement))* SEMICOLON?'/'?)) EOF
Please always put space after terms and remove useless parentheses:

```suggestion
    : sql_plus_command_no_semicolon? ((sql_plus_command | unit_statement) (SEMICOLON '/'? (sql_plus_command | unit_statement))* SEMICOLON? '/'?) EOF
```

2023-07-19 12:07 UTC, mfvitale commented
@KvanTTT  thanks for your suggestions. I have applied it.

2023-07-19 12:54 UTC, KvanTTT approved these changes

2023-07-19 12:56 UTC, KvanTTT commented
@kaby76 it looks like there is a problem with coverage CI task. Could you investigate please?

2023-07-19 17:54 UTC, mfvitale commented
> @kaby76 it looks like there is a problem with coverage CI task. Could you investigate please?

Seems same issue with CSharp.

2023-07-20 03:08 UTC, kaby76 commented
I mentioned this for another PR. https://github.com/antlr/grammars-v4/pull/3612#issuecomment-1636193153

And I opened an Issue for it. https://github.com/antlr/grammars-v4/issues/3597

I will turn off voverage computations for now as this will require a change to trcover, and will take time to make sure it works.

2023-07-20 09:17 UTC, merged

2023-08-21 15:39 UTC, Thracky commented
I should probably open an issue for this but SQLPlus commands do not require a terminating semicolon at all. See section 4.6.1 of the SQLPlus user guide here: https://docs.oracle.com/en/database/oracle/oracle-database/23/sqpug/SQL-Plus-basics.html#GUID-4F029548-6DD2-468F-B6E1-E6D6AA59014B

So if you have a file that starts with:

```
WHENEVER SQLERROR EXIT

SET ECHO ON

CREATE OR REPLACE PACKAGE ...
```

These changes make the parser bail out immediately on the `SET` and it is perfectly legal syntax for SQLPlus commands.