Fix PostgreSQL set operation precedence
antlr/grammars-v4 pull request #3567
Opened 2023-06-29 09:58 UTC by tisonkun

Comes from https://github.com/antlr/grammars-v4/pull/2378#discussion_r1246216426.

PG treats set ops in different precedence - INTERSECT is tighter than UNION and EXCEPT.

2023-06-29 11:29 UTC, tisonkun commented
test locally with `mvn test` under pg path and it passes all.

2023-06-30 01:13 UTC, tisonkun commented
@teverett is Windows build unstable? I check the CI log and it seems all about package installing instead of tests failure.

2023-07-11 13:04 UTC, KvanTTT requested changes
Please add a test that covers suggested changes.

2023-07-11 13:04 UTC, KvanTTT commented on sql/postgresql/PostgreSQLParser.g4
> +    : simple_select_pramary ((INTERSECT) all_or_distinct simple_select_pramary)*
Useless parentheses:

```suggestion
    : simple_select_pramary (INTERSECT all_or_distinct simple_select_pramary)*
```

2023-07-18 11:24 UTC, tisonkun commented
> Please add a test that covers suggested changes.

The current maven tests seems only test if the query parsed, not the result it parsed out. Shall I build the whole test kit from scratch to verify the op precedence result, or there are some existing tools/cases to leverage?

2023-07-19 10:19 UTC, KvanTTT approved these changes

2023-07-19 10:20 UTC, merged

2023-09-07 11:30 UTC, tisonkun commented on sql/postgresql/PostgreSQLParser.g4
> +simple_select_pramary
This should be a typo 🤣