PromQL: Added missing trigonometric functions
antlr/grammars-v4 pull request #3612
Opened 2023-07-14 08:37 UTC by Sageder

This pull request adds the missing trigonometric functions to the promql grammar: acos, acosh, asin, asinh, etc. You can see a list of functions in promql [here](https://prometheus.io/docs/prometheus/latest/querying/functions/#trigonometric-functions).

2023-07-14 10:02 UTC, KvanTTT requested changes
Please add/extend an [example](https://github.com/antlr/grammars-v4/tree/master/promql/examples) that covers suggested changes.

2023-07-14 10:39 UTC, Sageder commented
I added an example to function.txt:
```
sin(rate(http_requests_total[5m]))
```

2023-07-14 12:53 UTC, KvanTTT approved these changes

2023-07-14 12:54 UTC, merged

2023-07-14 17:53 UTC, kaby76 commented
The build is broken. https://github.com/antlr/grammars-v4/actions/runs/5554306328/jobs/10143937514#step:22:113

Please correct.

2023-07-15 09:57 UTC, KvanTTT commented
Sorry, I haven't noticed that. I'll fix it ASAP.