Fix typo in SCSS lexer
antlr/grammars-v4 pull request #3685
Opened 2023-09-02 04:22 UTC by InSyncWithFoo

Fixes #3684.

2023-09-11 09:02 UTC, KvanTTT requested changes

2023-09-11 09:02 UTC, KvanTTT commented on scss/ScssLexer.g4
> +VendorPrefix: '-moz-' | '-webkit-' | '-o-';
Please cover your changes with an example in [examples](https://github.com/antlr/grammars-v4/tree/master/scss/examples)

2023-09-12 21:32 UTC, teverett commented
@KvanTTT  ok to merge this?

2023-09-19 14:10 UTC, KvanTTT approved these changes

2023-09-19 14:11 UTC, merged

2023-09-19 14:11 UTC, KvanTTT commented
Yes, now it's ok. @InSyncWithFoo thanks for the contribution and welcome to ANTLR grammars repository!