Remove ambiguity in the url grammar
antlr/grammars-v4 pull request #3718
Opened 2023-09-21 12:24 UTC by bendrissou

This is to solve an [open issue](https://github.com/antlr/grammars-v4/issues/3715).

The dot character is allowed in strings. So there should not be a dot delimiter between strings. Otherwise, the parser would incorrectly parse the delimiter as part of the first string.

2023-09-21 12:47 UTC, KvanTTT requested changes
Please add an example that covers suggested changes to the [examples dir](https://github.com/antlr/grammars-v4/tree/master/url/examples).

2023-09-29 10:10 UTC, bendrissou commented
New example added.

2023-10-03 10:57 UTC, bendrissou commented
Hi @KvanTTT 

Any updates?

2023-10-03 11:09 UTC, KvanTTT approved these changes

2023-10-03 11:09 UTC, KvanTTT commented
Thanks for the contribution and welcome to ANTLR grammars repository!

2023-10-03 11:10 UTC, merged