[imporve] revise Positive Technologies‘s README.md
antlr/grammars-v4 pull request #3754
Opened 2023-10-06 12:58 UTC by caicancai

Positive Technologies currently seems to have mysql 8.0, can modify the README file, tell users

2023-10-06 13:08 UTC, caicancai commented
@KvanTTT

2023-10-06 13:42 UTC, KvanTTT requested changes

2023-10-06 13:42 UTC, KvanTTT commented on sql/mysql/README.md
> +* [Positive Technologies](Positive-Technologies) - A grammar created from the official documentation (5.6, 5.7,8.0)
Please add space after comma

```suggestion
* [Positive Technologies](Positive-Technologies) - A grammar created from the official documentation (5.6, 5.7, 8.0)
```

2023-10-06 13:42 UTC, KvanTTT commented on sql/mysql/Positive-Technologies/README.md
> +An ANTLR4 grammar for MySQL based on version 5.6 , 5.7 and 8.0 of
```suggestion
An ANTLR4 grammar for MySQL based on version 5.6, 5.7 and 8.0 of 
```

2023-10-06 13:42 UTC, KvanTTT commented on sql/mysql/Positive-Technologies/README.md
> +[http://dev.mysql.com/doc/refman/5.7/en/](http://dev.mysql.com/doc/refman/5.7/en/).                                       [http://dev.mysql.com/doc/refman/8.0/en/](http://dev.mysql.com/doc/refman/8.0
Line break is missing

```suggestion
[http://dev.mysql.com/doc/refman/5.7/en/](http://dev.mysql.com/doc/refman/5.7/en/).
[http://dev.mysql.com/doc/refman/8.0/en/](http://dev.mysql.com/doc/refman/8.0/en/).
```

2023-10-06 13:55 UTC, caicancai commented
@KvanTTT  fix

2023-10-08 12:39 UTC, KvanTTT approved these changes

2023-10-08 12:39 UTC, merged