cast expr
antlr/grammars-v4 pull request #3825
Opened 2023-11-15 02:34 UTC by gaoshihang

CAST is a function, we can use cast_expr to represent it, So we can traverse the tree better.

2023-11-15 12:52 UTC, KvanTTT requested changes
Welcome to ANTLR grammars repository and thanks for the fix!

But please add/extend an example to the [examples](https://github.com/antlr/grammars-v4/tree/master/sql/snowflake/examples) that covers suggested changes.

2023-11-15 15:33 UTC, gaoshihang commented
Hi @KvanTTT , I have added an example to it in the select.sql file, but don't know if it is right.
Please help review, if there is any issue, i will keep updating to this PR. 
Thanks!

2023-11-16 15:50 UTC, gaoshihang commented
Hi @KvanTTT , can you help me review on this? please

2023-11-19 16:40 UTC, KvanTTT approved these changes

2023-11-19 16:41 UTC, merged

2023-11-19 16:41 UTC, KvanTTT commented
Everything looks good. Thanks!

2023-11-20 02:18 UTC, gaoshihang commented
Thanks @KvanTTT !