Vba updates
antlr/grammars-v4 pull request #3881
Opened 2023-12-10 20:13 UTC by Beakerboy

The following module header is valid VBA

```
VERSION 5.00
Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} Login 
   Caption         =   "Please Log In"
   ClientHeight    =   1920
   ClientLeft      =   120
   ClientTop       =   465
   ClientWidth     =   2295
   OleObjectBlob   =   "Login.frx":0000
   StartUpPosition =   1  'CenterOwner
End
```

I changed the file to make the CLASS optional, allowed for an optional GUID after Begin, and allowed the attribute to have colon followed by a literal.

2023-12-11 11:14 UTC, kaby76 commented
The TypeScript target testing is broken. I have a fix in https://github.com/antlr/grammars-v4/pull/3883. Please fast forward/rebase after it's merged, otherwise testing for your PR will fail. Sorry for the inconvenience.

2023-12-12 13:01 UTC, KvanTTT requested changes
Thanks for the contribtuion and welcome to ANTLR grammars repository!

2023-12-12 13:50 UTC, Beakerboy commented on vba/vba.g4
> +    : VERSION WS DOUBLELITERAL WS (CLASS)?
Removed. Thanks for the feedback.

2023-12-12 15:10 UTC, teverett commented
@Beakerboy  @KvanTTT  ok to pull this?

2023-12-12 15:18 UTC, Beakerboy commented
Yes from me

2023-12-12 15:21 UTC, KvanTTT approved these changes

2023-12-12 16:35 UTC, teverett commented
@Beakerboy thanks!

2023-12-12 16:36 UTC, merged