fetch_statement bug fix
antlr/grammars-v4 pull request #3909
Opened 2023-12-22 10:36 UTC by langio

Add collection_expression and variable_or_collection rule that used by fetch_statement to resolve scenarios where the variable_name is a collection

2023-12-22 13:31 UTC, KvanTTT requested changes

2023-12-22 13:31 UTC, KvanTTT commented on sql/plsql/PlSqlParser.g4
> +    : collation_name ('(' expression ')' ('.' general_element_part)*)
Outer parentheses look redundant:

```suggestion
    : collation_name '(' expression ')' ('.' general_element_part)*
```

2023-12-22 13:56 UTC, langio commented on sql/plsql/PlSqlParser.g4
> +    : collation_name ('(' expression ')' ('.' general_element_part)*)
yes, i have fixed it.

2023-12-26 16:25 UTC, KvanTTT approved these changes

2023-12-26 16:27 UTC, merged