[PlSql] Many fixes and additions
antlr/grammars-v4 pull request #3943
Opened 2024-01-25 16:19 UTC by DmitryMikhailovich

2024-01-28 11:26 UTC, KvanTTT reviewed
> It was tiresome to create separate PRs for each of the following 35 changes, so, please, forgive me for this huge PR🙂

Thanks for the PR with such a clear and detailed history! I treat it an example for other contributors. But I see some commits are covered with tests some are not. Is it intentionally?

2024-01-28 12:34 UTC, KvanTTT requested changes

2024-01-31 13:56 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlLexer.g4
> +INQUIRY_DIRECTIVE: '$$' (SIMPLE_LETTER | '_' )+;
It's a habit I've developed working on another grammar. 
Fixed.

2024-01-31 13:56 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    : ALTER FUNCTION function_name (EDITIONABLE | NONEDITIONABLE | COMPILE DEBUG? compiler_parameters_clause* (REUSE SETTINGS)? )
Fixed.

2024-01-31 13:56 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    ) package_obj_body* (BEGIN seq_of_statements (EXCEPTION exception_handler+)? )? END package_name?
Fixed.

2024-01-31 14:07 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    : PARTITION partition_name? VALUES LESS THAN '(' (literal (',' literal)* | TIMESTAMP literal (',' TIMESTAMP literal)* ) ')' segment_attributes_clause?
Fixed (list extracted into `index_partitioning_values_list` rule)

2024-01-31 14:07 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +      | LIBRARY identifier )
Fixed.

2024-01-31 14:07 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +      | procedure_body)+
Fixed.

2024-01-31 14:08 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    | expression '.' TRIM ('(' index+=expression ')')?
Fixed.

2024-01-31 14:08 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +      | hier_alias=object_name) TO condition
Fixed.

2024-01-31 14:10 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    | unary_expression '.' (EXISTS | NEXT | PRIOR) '(' index+=expression ')'
Fixed.

2024-01-31 14:10 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +      (with_factoring_clause (',' with_factoring_clause)* )?
Fixed.

2024-01-31 14:11 UTC, DmitryMikhailovich commented on sql/plsql/PlSqlParser.g4
> +    | REFERENCES referencing_element*
Fixed.
You mean to clarify usage of `REFERENCES` (add a comment into grammar code)?

2024-01-31 14:17 UTC, DmitryMikhailovich commented
> > It was tiresome to create separate PRs for each of the following 35 changes, so, please, forgive me for this huge PR🙂
> 
> Thanks for the PR with such a clear and detailed history! I treat it an example for other contributors.
> 
> But I see some commits are covered with tests some are not. Is it intentionally?

I've covered with tests (examples) the most non-trivial, obscure and undocumented cases. I can add examples for other changes, if it is necessary.

2024-02-05 14:20 UTC, KvanTTT approved these changes

2024-02-05 14:23 UTC, KvanTTT reviewed
> I can add examples for other changes, if it is necessary.

Ideally, we should have examples for all changes, and if it doesn't bother you, please add. Otherwise, I'll merge the PR without these tests, it's anyway very good.

2024-02-05 14:25 UTC, KvanTTT commented
@teverett please leave it to me, the PR should be merged using `Rebase and merge` method, it contains very clear commits.

2024-02-07 10:22 UTC, DmitryMikhailovich commented
> > I can add examples for other changes, if it is necessary.
> 
> Ideally, we should have examples for all changes, and if it doesn't bother you, please add. Otherwise, I'll merge the PR without these tests, it's anyway very good.

I'll add missing examples by the end of this week.

2024-02-07 20:21 UTC, teverett commented
@KvanTTT  leaving this on to you to merge :)

2024-02-10 17:30 UTC, DmitryMikhailovich commented
- [de1be77](https://github.com/antlr/grammars-v4/pull/3943/commits/de1be77987b77730f898495f02783565d6ea3c01) Fixed property list for package procedure definition and declaration (haven't read [docs ](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/procedure-declaration-and-definition.html#GUID-9A48D7CE-3720-46A4-B5CA-C2250CA86AF2) attentively). 
![image](https://github.com/antlr/grammars-v4/assets/10853270/88237c40-1b7c-4726-911f-14789226d108)
- [973692d](https://github.com/antlr/grammars-v4/pull/3943/commits/973692d500854094dccfa1db5ead7d9231c921c6) Added optional `hierarchies_clause` after analytic view name in `FROM`.
- [1741015](https://github.com/antlr/grammars-v4/pull/3943/commits/17410158da678a77c965643c30ed3d2600267df8) Added rule for `SQL%BULK_ROWCOUNT` (in [5c8390c](https://github.com/antlr/grammars-v4/pull/3943/commits/5c8390c31a2d354b51b0d6e30189ee20779fa2de) I've added only lexer and forgot about parser).
- [bca4634](https://github.com/antlr/grammars-v4/pull/3943/commits/bca46345fc29e79bf34bc2587c49709481faa7b9) Added examples for all changes.

2024-02-10 19:00 UTC, DmitryMikhailovich commented
[60ef94a](https://github.com/antlr/grammars-v4/pull/3943/commits/60ef94affcb310b67aca596fbc7e189308ad8a6d) and [511143d](https://github.com/antlr/grammars-v4/pull/3943/commits/511143d25d14df9497a6ce9d1221ac508b2fbc7d)
Fixed regressions:
- added full syntax for `parallel_enable_clause` and `streaming_clause` to function declaration.
- `PIPELINED` and `DETERMINISTIC` options in function definition may be in any order with other function properties.
- removed `streaming_clause` from `create_function_body` which I've added in [30bb70f](https://github.com/antlr/grammars-v4/pull/3943/commits/30bb70fb682c3880de3423107424b5608d72996c) - confused create function rule with function spec rule.
Example sql/plsql/examples/create_package05.sql covers those changes and compiles as valid package (tested on live Oracle 19).

[8fc5378](https://github.com/antlr/grammars-v4/pull/3943/commits/8fc53788c6489fffa505f199e021ad005ea01011) Support any `expression` as a target of `IS [NOT] JSON`.

[aaa00b4](https://github.com/antlr/grammars-v4/pull/3943/commits/aaa00b4197499f4b2bc99365574e6b344aacda06) fixed typos and commented out some code in my examples (`sql_script` rule does not support cases, when there is other statement(s) after `/`

2024-02-12 13:27 UTC, KvanTTT approved these changes

2024-02-12 13:27 UTC, merged

2024-02-12 13:27 UTC, KvanTTT commented
Thanks a lot!

2024-02-17 18:57 UTC, Naros commented
After these were applied to master, running `mvn test` in the `plsql` directory, the `alter_database.sql` example files with errors.  Are we certain that there are not any other regressions that may have been missed @DmitryMikhailovich  and @KvanTTT ?

2024-02-17 19:30 UTC, KvanTTT commented
It's quite strange because the current build on master is green.

2024-02-18 07:45 UTC, Naros commented
> It's quite strange because the current build on master is green.

I agree, I noticed the CI is green.  If you run `mvn test` from within the `plsql` directory manually, do you observe the same issue @KvanTTT ?