Added type hints to constants
antlr/grammars-v4 pull request #3944
Opened 2024-01-26 02:19 UTC by Xenios91

Constants should be able to have type hints, I added this.

2024-01-27 21:06 UTC, KvanTTT requested changes

2024-01-27 21:06 UTC, KvanTTT commented on vba/vba.g4
> +    : ambiguousIdentifier typeHint? (WS asTypeClause)? WS? EQ WS? valueStmt (typeHint?)
Please remove redundant parentheses

```suggestion
    : ambiguousIdentifier typeHint? (WS asTypeClause)? WS? EQ WS? valueStmt typeHint?
```

2024-02-01 22:48 UTC, teverett commented
@Xenios91  thanks!

2024-02-15 19:17 UTC, KvanTTT requested changes
Please fix merge conflict with master branch

2026-06-18 15:17 UTC, Beakerboy commented
@Xenios91 I just submitted a completely rewritten grammar for vba7.1. That likely already includes a fix for this issue.

2026-06-24 11:40 UTC, closed without merging